### ISSUE TITLE
 No mapping found for HTTP request with URI [/text2/logincheck.action] in DispatcherServlet with name 'springMvc'

### ISSUE THREAD

**Issue by ranhaoliu** [chiuwingyan/house#18]
DEBUG [http-nio-8080-exec-2] - Did not find handler method for [/logincheck.action]
 WARN [http-nio-8080-exec-2] - No mapping found for HTTP request with URI [/text2/logincheck.action] in DispatcherServlet with name 'springMvc'

**Comment by Weilvnang** [comment]
这是来自QQ邮箱的假期自动回复邮件。您的邮件我已经收到，我会尽快查收，谢谢！
